version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-sqlserver-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    restart: always
